// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApJI06ily-qq6USw-asz3CheG88ghamJ8',
    appId: '1:266482313771:web:a7f4f46e0e226ead9b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    authDomain: 'offora-private-limited.firebaseapp.com',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    measurementId: 'G-Z2TC531M2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDch_sMeS2g9voe2gybDhyYepUB4cXENAg',
    appId: '1:266482313771:android:cdb73d1bda7fb0fb9b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    storageBucket: 'offora-private-limited.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYl1p2D7yY-G_InyfYV8ZKuEAOf72qcPM',
    appId: '1:266482313771:ios:2b15e309473df0609b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    iosClientId: '266482313771-v7vmgsjmg9eo1b639rqu75032tikrbad.apps.googleusercontent.com',
    iosBundleId: 'com.example.offora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYl1p2D7yY-G_InyfYV8ZKuEAOf72qcPM',
    appId: '1:266482313771:ios:2b15e309473df0609b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    iosClientId: '266482313771-v7vmgsjmg9eo1b639rqu75032tikrbad.apps.googleusercontent.com',
    iosBundleId: 'com.example.offora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApJI06ily-qq6USw-asz3CheG88ghamJ8',
    appId: '1:266482313771:web:7d62de082c8bb7339b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    authDomain: 'offora-private-limited.firebaseapp.com',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    measurementId: 'G-VB1PC9DBNH',
  );
}
