// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcBRA9Wtncwi14BkWuzXXUW3P3RPOpKo8',
    appId: '1:266482313771:web:1816917f7eb0ba3c9b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    authDomain: 'offora-private-limited.firebaseapp.com',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    measurementId: 'G-LW1L9P3JVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDch_sMeS2g9voe2gybDhyYepUB4cXENAg',
    appId: '1:266482313771:android:21bb4350561cf9d09b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    storageBucket: 'offora-private-limited.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDrKuJreHSyr_oEDGT0mf60SKglMn56Zo',
    appId: '1:266482313771:ios:7cae862e1778c1099b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    iosClientId: '266482313771-rqh7v18rerklqjmjc8duiiqlgc270v2t.apps.googleusercontent.com',
    iosBundleId: 'com.offora.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDrKuJreHSyr_oEDGT0mf60SKglMn56Zo',
    appId: '1:266482313771:ios:7cae862e1778c1099b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    iosClientId: '266482313771-rqh7v18rerklqjmjc8duiiqlgc270v2t.apps.googleusercontent.com',
    iosBundleId: 'com.offora.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcBRA9Wtncwi14BkWuzXXUW3P3RPOpKo8',
    appId: '1:266482313771:web:1816917f7eb0ba3c9b986e',
    messagingSenderId: '266482313771',
    projectId: 'offora-private-limited',
    authDomain: 'offora-private-limited.firebaseapp.com',
    storageBucket: 'offora-private-limited.firebasestorage.app',
    measurementId: 'G-LW1L9P3JVG',
  );

}